import React, { useState } from 'react';
import { Button, Select, DatePicker, App } from 'antd';
import { FileTextOutlined, TeamOutlined, FileDoneOutlined, CreditCardOutlined, AuditOutlined, ArrowDownOutlined, FilterOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import PageTitle from '../../components/ui/PageTitle';
import DataTable from '../../components/ui/DataTable';
import StatusTag from '../../components/ui/StatusTag';
import { COLORS } from '../../constants/theme';
import { DATA_TYPES, FORMATS, REGIONS } from '../../data/modules';
import { useCollection, useLogChange, useReload } from '../../store/AdminStore';
import { api, downloadFromApi } from '../../api/client';
import { formatDateTime, formatSize } from '../../utils/format';

const TYPE_ICONS = { Claims: <FileTextOutlined />, Users: <TeamOutlined />, Survey: <FileDoneOutlined />, Payments: <CreditCardOutlined />, 'Audit Logs': <AuditOutlined /> };

/**
 * Data Download -- pick data sets, date range and region, choose a format,
 * "Generate Download": admin-service builds each file from the database,
 * keeps it for 7 days (Download History) and it is downloaded straight away.
 */
const DataDownloadPage = () => {
    const { message } = App.useApp();
    const downloads = useCollection('downloads');
    const logChange = useLogChange();
    const reload = useReload();

    const [format, setFormat] = useState(undefined);
    const [types, setTypes] = useState(['Claims']);
    const [from, setFrom] = useState(dayjs().subtract(30, 'day'));
    const [to, setTo] = useState(dayjs());
    const [region, setRegion] = useState(undefined);
    const [busy, setBusy] = useState(false);

    const generate = async () => {
        if (!format) return message.warning('Select a format first.');
        if (!types.length) return message.warning('Select at least one data set.');
        if (!from || !to) return message.warning('Select the date range.');
        setBusy(true);
        try {
            const files = await api.post('/downloads', { format, types, from: from.format('YYYY-MM-DD'), to: to.format('YYYY-MM-DD'), region });
            for (const f of files) {
                await downloadFromApi(`/downloads/${f.id}/file`, f.fileName);
                logChange('Data Download', `${f.dataType} export`, '—', `${f.fileName} (${f.rows} rows)`);
            }
            message.success(`${files.length} file(s) generated`);
        } catch (err) {
            message.error(err.message);
        } finally {
            setBusy(false);
            reload(['downloads']);
        }
        return undefined;
    };

    const redownload = async (d) => {
        if (d.status !== 'Ready') return message.warning('This file has expired — generate it again.');
        try {
            await downloadFromApi(`/downloads/${d.id}/file`, d.fileName);
            message.success(`Downloading ${d.fileName}`);
        } catch (err) {
            message.error(err.message);
            reload(['downloads']);
        }
        return undefined;
    };

    const toggleType = (t) => setTypes((list) => (list.includes(t) ? list.filter((x) => x !== t) : [...list, t]));

    const columns = [
        { title: 'File Name', dataIndex: 'fileName' },
        { title: 'Data Type', dataIndex: 'dataType' },
        { title: 'Generated By', dataIndex: 'by' },
        { title: 'Generated On', dataIndex: 'at', render: formatDateTime },
        { title: 'File Size', dataIndex: 'sizeKb', render: formatSize },
        { title: 'Status', dataIndex: 'status', render: (s) => <StatusTag status={s} minWidth={70} />, align: 'center' },
        { title: 'Action', align: 'center', render: (_, d) => <Button type="text" size="small" aria-label={`Download ${d.fileName}`} icon={<ArrowDownOutlined style={{ color: d.status === 'Ready' ? COLORS.success : COLORS.textMuted }} />} onClick={() => redownload(d)} /> },
    ];

    const step = (n, title, children, last) => (
        <div className="flex-1 min-w-[220px] px-3" style={{ borderRight: last ? 'none' : `1px solid ${COLORS.border}` }}>
            <h3 className="text-[14px] font-semibold m-0 mb-2">{n}. {title}</h3>
            {children}
        </div>
    );

    return (
        <>
            <PageTitle
                title="Data Download"
                extra={(
                    <div className="flex items-end gap-2">
                        <label className="flex flex-col gap-0.5"><span className="text-[13px] font-semibold">Select Format</span>
                            <Select placeholder="Select Format" value={format} onChange={setFormat} options={FORMATS.map((f) => ({ value: f, label: f }))} style={{ width: 130 }} />
                        </label>
                        <Button type="primary" onClick={generate} loading={busy}>Generate Download</Button>
                    </div>
                )}
            />

            <div className="filter-bar flex flex-wrap gap-y-3 rounded-md py-3 mb-3" style={{ background: '#fff', border: `1px solid ${COLORS.border}` }}>
                {step(1, 'Select Data', (
                    <div className="flex flex-wrap gap-2">
                        {DATA_TYPES.map((t) => {
                            const on = types.includes(t);
                            return (
                                <button key={t} type="button" onClick={() => toggleType(t)} aria-pressed={on} className="flex flex-col items-center justify-center gap-0.5 rounded text-[10px] font-medium" style={{ width: 56, height: 50, color: COLORS.primary, background: on ? COLORS.bgSoftBlue : '#F4F4F4', border: `1px solid ${on ? COLORS.primary : '#E2E2E2'}` }}>
                                    <span className="text-[15px]">{TYPE_ICONS[t]}</span>{t}
                                </button>
                            );
                        })}
                    </div>
                ))}
                {step(2, 'Select Date Range', (
                    <div className="flex items-center gap-1.5">
                        <DatePicker value={from} onChange={setFrom} format="DD MMMM YYYY" disabledDate={(d) => to && d.isAfter(to)} style={{ width: 150 }} />
                        <span>—</span>
                        <DatePicker value={to} onChange={setTo} format="DD MMMM YYYY" disabledDate={(d) => from && d.isBefore(from)} style={{ width: 150 }} />
                    </div>
                ))}
                {step(3, 'Select', (
                    <Select allowClear placeholder="Select" value={region} onChange={setRegion} suffixIcon={<FilterOutlined />} options={REGIONS.map((r) => ({ value: r, label: `${r} Region` }))} style={{ width: 170 }} />
                ), true)}
            </div>

            <DataTable title="Download History" columns={columns} dataSource={downloads.items} pageSize={6} scrollX={900} />
        </>
    );
};

export default DataDownloadPage;
